default: true

# Allow inline HTML
MD033: false

# Ignore line length rules (as Prettier will format for these).
MD013: false

# Allow duplicate headings (e.g. "Further reading")
MD024: false

# Would like to require fenced code blocks but this doesn't work with lists or
# code blocks in footnotes.
MD046: false

# Skip rule around space inside code spans which doesn't work with fenced code blocks in footnotes.
MD038: false
