---
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.7
    hooks:
      - id: typos

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
